// Define a list of German phrases and their Danish translations
final List<Map<String, String>> phrases = [
{'german': 'Wie geht es dir?', 'danish': 'Hvordan har du det?'},
{'german': 'Guten Morgen!', 'danish': 'Godmorgen!'},
{'german': 'Wie heißt du?', 'danish': 'Hvad hedder du?'},
{'german': 'Ich verstehe nicht.', 'danish': 'Jeg forstår ikke.'},
{'german': 'Kommst du mit?', 'danish': 'Kommer du med?'},
{'german': 'Hast du Zeit?', 'danish': 'Har du tid?'},
{'german': 'Was machst du heute?', 'danish': 'Hvad laver du i dag?'},
{'german': 'Ich habe keine Ahnung.', 'danish': 'Jeg har ingen idé.'},
{'german': 'Entschuldigung, wo ist die Toilette?', 'danish': 'Undskyld, hvor er toilettet?'},
{'german': 'Wie spät ist es?', 'danish': 'Hvad tid er det?'},
{'german': 'Ich bin müde.', 'danish': 'Jeg er træt.'},
{'german': 'Ich bin hungrig.', 'danish': 'Jeg er sulten.'},
{'german': 'Hast du Hunger?', 'danish': 'Er du sulten?'},
{'german': 'Was möchtest du essen?', 'danish': 'Hvad vil du spise?'},
{'german': 'Es ist zu spät.', 'danish': 'Det er for sent.'},
{'german': 'Wann kommst du zurück?', 'danish': 'Hvornår kommer du tilbage?'},
{'german': 'Ich habe Durst.', 'danish': 'Jeg er tørstig.'},
{'german': 'Kannst du mir helfen?', 'danish': 'Kan du hjælpe mig?'},
{'german': 'Ich habe es vergessen.', 'danish': 'Jeg har glemt det.'},
{'german': 'Hast du einen Moment?', 'danish': 'Har du et øjeblik?'},
{'german': 'Ich bin gleich zurück.', 'danish': 'Jeg er snart tilbage.'},
{'german': 'Bist du sicher?', 'danish': 'Er du sikker?'},
{'german': 'Kann ich dir etwas bringen?', 'danish': 'Kan jeg hente noget til dig?'},
{'german': 'Wann hast du Feierabend?', 'danish': 'Hvornår har du fri?'},
{'german': 'Was machst du am Wochenende?', 'danish': 'Hvad laver du i weekenden?'},
{'german': 'Ich muss gehen.', 'danish': 'Jeg må gå.'},
{'german': 'Was willst du tun?', 'danish': 'Hvad vil du gøre?'},
{'german': 'Es tut mir leid.', 'danish': 'Jeg er ked af det.'},
{'german': 'Kannst du das wiederholen?', 'danish': 'Kan du gentage det?'},
{'german': 'Kommst du mit zum Essen?', 'danish': 'Kommer du med til at spise?'},
{'german': 'Woher kommst du?', 'danish': 'Hvor kommer du fra?'},
{'german': 'Ich habe keine Zeit.', 'danish': 'Jeg har ikke tid.'},
{'german': 'Wir sehen uns später.', 'danish': 'Vi ses senere.'},
{'german': 'Was ist los?', 'danish': 'Hvad sker der?'},
{'german': 'Ich freue mich darauf.', 'danish': 'Jeg ser frem til det.'},
{'german': 'Wie lange bleibst du?', 'danish': 'Hvor længe bliver du?'},
{'german': 'Kann ich dir helfen?', 'danish': 'Kan jeg hjælpe dig?'},
{'german': 'Wo bist du?', 'danish': 'Hvor er du?'},
{'german': 'Ich bin beschäftigt.', 'danish': 'Jeg er travl.'},
{'german': 'Hast du das gesehen?', 'danish': 'Så du det?'},
{'german': 'Ich habe keine Lust.', 'danish': 'Jeg har ikke lyst.'},
{'german': 'Hast du einen Plan?', 'danish': 'Har du en plan?'},
{'german': 'Wann beginnt der Film?', 'danish': 'Hvornår begynder filmen?'},
{'german': 'Ich habe keine Idee.', 'danish': 'Jeg har ingen idé.'},
{'german': 'Das ist interessant.', 'danish': 'Det er interessant.'},
{'german': 'Was ist dein Lieblingsessen?', 'danish': 'Hvad er din yndlingsmad?'},
{'german': 'Ich bin froh, dich zu sehen.', 'danish': 'Jeg er glad for at se dig.'},
{'german': 'Ich bin gerade unterwegs.', 'danish': 'Jeg er på vej.'},
{'german': 'Wir können später sprechen.', 'danish': 'Vi kan tale senere.'},
{'german': 'Was möchtest du trinken?', 'danish': 'Hvad vil du drikke?'},
{'german': 'Es ist sehr kalt draußen.', 'danish': 'Det er meget koldt udenfor.'},
{'german': 'Ich bin sehr müde.', 'danish': 'Jeg er meget træt.'},
{'german': 'Es geht mir gut.', 'danish': 'Jeg har det godt.'},
{'german': 'Ich bin hungrig und müde.', 'danish': 'Jeg er sulten og træt.'},
{'german': 'Kannst du mir sagen, wo es ist?', 'danish': 'Kan du sige mig, hvor det er?'},
{'german': 'Ich brauche eine Pause.', 'danish': 'Jeg har brug for en pause.'},
{'german': 'Es ist nicht weit von hier.', 'danish': 'Det er ikke langt herfra.'},
{'german': 'Ich habe es nicht gewusst.', 'danish': 'Jeg vidste det ikke.'},
{'german': 'Wie viel kostet das?', 'danish': 'Hvor meget koster det?'},
{'german': 'Wann hast du Geburtstag?', 'danish': 'Hvornår har du fødselsdag?'},
{'german': 'Das ist eine gute Idee.', 'danish': 'Det er en god idé.'},
{'german': 'Ich habe es schon gemacht.', 'danish': 'Jeg har allerede gjort det.'},
{'german': 'Wie lange dauert das?', 'danish': 'Hvor lang tid tager det?'},
{'german': 'Ich habe es vergessen.', 'danish': 'Jeg har glemt det.'},
{'german': 'Kannst du mir das erklären?', 'danish': 'Kan du forklare det for mig?'},
{'german': 'Ich bin froh, dass du da bist.', 'danish': 'Jeg er glad for, at du er her.'},
{'german': 'Hast du morgen Zeit?', 'danish': 'Har du tid i morgen?'},
{'german': 'Das ist kein Problem.', 'danish': 'Det er ikke noget problem.'},
{'german': 'Ich muss nach Hause.', 'danish': 'Jeg skal hjem.'},
{'german': 'Es ist mir egal.', 'danish': 'Det er mig ligegyldigt.'},
{'german': 'Wie war dein Tag?', 'danish': 'Hvordan var din dag?'},
{'german': 'Ich bin nicht sicher.', 'danish': 'Jeg er ikke sikker.'},
{'german': 'Das ist sehr nett von dir.', 'danish': 'Det er meget venligt af dig.'},
{'german': 'Wie kann ich dir helfen?', 'danish': 'Hvordan kan jeg hjælpe dig?'},
{'german': 'Ich bin zu spät.', 'danish': 'Jeg er for sent på den.'},
{'german': 'Es ist alles in Ordnung.', 'danish': 'Det er alt i orden.'},
{'german': 'Ich habe etwas für dich.', 'danish': 'Jeg har noget til dig.'},
{'german': 'Das ist sehr teuer.', 'danish': 'Det er meget dyrt.'},
{'german': 'Ich warte auf dich.', 'danish': 'Jeg venter på dig.'},
{'german': 'Es ist viel zu tun.', 'danish': 'Der er meget at gøre.'},
{'german': 'Kann ich dir etwas helfen?', 'danish': 'Kan jeg hjælpe dig med noget?'},
{'german': 'Hast du eine Idee?', 'danish': 'Har du en idé?'},
{'german': 'Ich werde es probieren.', 'danish': 'Jeg vil prøve.'},
{'german': 'Es war schön, dich zu treffen.', 'danish': 'Det var rart at møde dig.'},
{'german': 'Ich bin hungrig und müde.', 'danish': 'Jeg er sulten og træt.'},
{'german': 'Es tut mir leid für dich.', 'danish': 'Jeg er ked af det for dig.'},
{'german': 'Ich bin froh, dich kennenzulernen.', 'danish': 'Jeg er glad for at møde dig.'},
{'german': 'Das ist wirklich schön.', 'danish': 'Det er virkelig smukt.'},
{'german': 'Lass uns zusammen gehen.', 'danish': 'Lad os gå sammen.'},
{'german': 'Ich muss jetzt gehen.', 'danish': 'Jeg må gå nu.'},
{'german': 'Kannst du mir helfen, das zu finden?', 'danish': 'Kan du hjælpe mig med at finde det?'},
{'german': 'Ich möchte etwas essen.', 'danish': 'Jeg vil gerne spise noget.'},
{'german': 'Wie war das Wochenende?', 'danish': 'Hvordan var weekenden?'},
{'german': 'Ich habe keine Lust, heute rauszugehen.', 'danish': 'Jeg har ikke lyst til at gå ud i dag.'},
{'german': 'Kommst du zur Party?', 'danish': 'Kommer du til festen?'},
{'german': 'Ich muss das sofort erledigen.', 'danish': 'Jeg skal ordne det med det samme.'},
{'german': 'Das macht Spaß!', 'danish': 'Det er sjovt!'},
];