name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.4'

    - name: Install dependencies
      run: |
        flutter pub get

    - name: Build Flutter Web
      run: |
        flutter build web --release

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: build/web
        token: ${{ secrets.GITHUB_TOKEN }}
